course_type:
  maximum: 50
course:
  title: 20
  overview: 20
  description: 10
user:
  first_name:
    maximum: 20
    regex: /\A[A-Za-z\s]+\z/
  last_name:
    maximum: 20
  email:
    regex: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i