course_type:
  maximum: 50
course:
  title: 100
  overview: 150
  description: 200
first_name:
  maximum: 20
last_name:
  maximum: 20
users:
  per_page: 20
search:
  per_page: 5
user_courses:
  per_page: 8
lesson_step:
  default: 2
lesson_type: { video: 1, question: 2 }
