course_type:
  maximum: 50
course:
  title: 100
  overview: 150
  description: 200
first_name:
  maximum: 20
last_name:
  maximum: 20
search:
  per_page: 6
lesson_step:
  default: 1
lesson_type: { video: 1, question: 2 }
